import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import Link from "next/link";
import { Button } from "@/components/ui/Button";
import SearchIcon from "@/components/icons/SearchIcon";
import CheckCircleIcon from "@/components/icons/CheckCircleIcon";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen flex flex-col">
          <header className="flex h-14 items-center border-b px-4">
            <Link className="flex items-center gap-2 font-semibold" href="#">
              <CheckCircleIcon />
              <span className="">MindfulMemos</span>
            </Link>
            <Button className="ml-auto h-8 w-8" size="icon" variant="ghost">
              <SearchIcon />
              <span className="sr-only">Toggle search</span>
            </Button>
          </header>
          {children}
        </div>
      </body>

      <SpeedInsights />
    </html>
  );
}
